# Generated by Django 4.1.3 on 2022-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lead_alter_user_password_delete_curatorlead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True, verbose_name='slug'),
        ),
    ]
