# Generated by Django 4.1.3 on 2022-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True, verbose_name='slug'),
        ),
    ]
