# Generated by Django 4.1.3 on 2022-12-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='access',
            new_name='is_active',
        ),
    ]
