# Generated by Django 4.1.3 on 2022-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='presentation video'),
        ),
    ]
