# Generated by Django 4.1.3 on 2022-12-18 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lessons.models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_access', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40, verbose_name='lesson name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('video', models.CharField(blank=True, max_length=100, null=True, verbose_name='video link')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('home_task', models.TextField(blank=True, null=True)),
                ('test', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lessons.models.Material.file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf']), users.validators.validate_size])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lessons.lesson')),
            ],
        ),
    ]
