# Generated by Django 4.1.3 on 2022-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
